name: CD

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write # para crear la release en GitHub

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Install build deps
        run: uv sync --dev

      - name: Build package
        run: uv build

      - name: Publish to PyPI
        env:
          UV_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish --token "$UV_PYPI_TOKEN"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
