name: CI

on:
  pull_request:
    branches: ["main", "develop"]
  push:
    branches: ["main", "develop"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality:
    name: Code Quality (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Sync environment
        run: uv sync --all-extras

      - name: Check code formatting
        run: uv run ruff format --check .

      - name: Run linters
        run: uv run ruff check .

      - name: Run type checker
        run: uv run mypy --strict .

      - name: Run tests with coverage
        run: |
          uv run pytest -v \
            --cov=src \
            --cov-report=term-missing \
            --cov-fail-under=70

      - name: Build documentation
        if: hashFiles('docs/**') != ''
        run: |
          if [ -f "mkdocs.yml" ]; then
            uv run mkdocs build --strict
          elif [ -f "docs/conf.py" ]; then
            uv run sphinx-build -W docs docs/_build
          fi

      - name: Summary
        if: always()
        run: |
          echo "✅ CI completed for Python ${{ matrix.python-version }}"
          echo "📊 Check coverage reports in artifacts"
