name: Pre-Release

on:
  push:
    branches: [develop]

permissions:
  contents: write
  issues: write

jobs:
  pre-release:
    name: Pre-Release (RC)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install python-semantic-release==9.*

      - name: Pre-Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release version --prerelease
          semantic-release publish --prerelease
